export const CANONICAL_MARKETS = [
    'Alternative Corners',
    'Asian Total Cards',
    'Bet Builder',
    'Bookings Spread',
    'Bookings Totals',
    'Both Teams To Score',
    'Card Handicap',
    'Corner Handicap',
    'Corner Match Bet',
    'Corner Spread',
    'Corners 2-Way',
    'Corners Match Bet',
    'Corners Spread',
    'Corners Totals',
    'Correct Score',
    'Double Chance',
    'Draw No Bet',
    'First Goal Scorer',
    'First Team to Score',
    'Free Kicks',
    'Goal Kicks',
    'Goalkeeper Saves',
    'Half Time Full Time',
    'Half Time Result',
    'Match Corners',
    'Match Offsides',
    'Match Result',
    'Match Shots',
    'Match Shots On Target',
    'Match Tackles',
    'Number of Cards In Match',
    'Outrights',
    'Player Accurate Passes',
    'Player Aerial Duels Won',
    'Player Assists',
    'Player Blocks',
    'Player Booked First',
    'Player Cards',
    'Player Clearances',
    'Player Crosses',
    'Player Dribbles',
    'Player Fast Break Shots',
    'Player Fouls Committed',
    'Player Fouls Won',
    'Player Free Kick Shots',
    'Player Free Kick SOT',
    'Player Goal From Header',
    'Player Goal From Outside Box',
    'Player Goals',
    'Player H2H',
    'Player Headed Shots',
    'Player Headed Shots On Target',
    'Player Interceptions',
    'Player Key Passes',
    'Player Offsides',
    'Player Passes',
    'Player Red Card',
    'Player Score 2+ Goals',
    'Player Score 3+ Goals',
    'Player Score or Assist',
    'Player Set Piece Shots',
    'Player Set Piece SOT',
    'Player Shots From Outside Box',
    'Player Shots On Target',
    'Player Shots Total',
    'Player SOT Outside Box',
    'Player Tackles',
    'Player Throw-in Shots',
    'Player To Assist',
    'Player To Score or Assist',
    'Player Yellow Card',
    'Team Cards',
    'Team Corners',
    'Team Corners 1st Half',
    'Team Corners 2nd Half',
    'Team To Get Most Corners',
    'Team Fouls',
    'Team Free Kicks',
    'Team Goal Kicks',
    'Team Goals',
    'Team Goals Outside Box',
    'Team Headed Goals',
    'Team Headed Shots',
    'Team Headed Shots On Target',
    'Team Offsides',
    'Team Red Cards',
    'Team Saves',
    'Team Shots',
    'Team Shots On Target',
    'Team Shots On Target Outside Box',
    'Team Shots Outside Box',
    'Team Tackles',
    'Team Throw-ins',
    'Team Total Goals',
    'Throw-ins',
    'To Be Booked First',
    'To Score First',
    'Total Cards',
    'Total Corners',
    'Total Fouls',
    'Total Free Kicks',
    'Total Goal Kicks',
    // Canonical name for match total goals is "Goal Line" (matches alert auto-imports; the old
    // "Total Goals" spelling split the same market into two analytics buckets).
    'Goal Line',
    'Total Goals Outside Box',
    'Total Headed Goals',
    'Total Headed Shots',
    'Total Headed Shots On Target',
    'Total Offsides',
    'Total Penalties',
    'Total Red Cards',
    'Total Saves',
    'Total Shots',
    'Total Shots On Target',
    'Total Shots On Target Outside Box',
    'Total Shots Outside Box',
    'Total Tackles',
    'Total Throw-ins'
];

export const MARKET_DIRECTIONS: Record<string, string> = {
    'Asian Total Cards': 'both',
    'Bet Builder': 'none',
    'Bookings Totals': 'both',
    'Both Teams To Score': 'both',
    'Corners 2-Way': 'both',
    'Corners Totals': 'both',
    'Correct Score': 'both',
    'Double Chance': 'both',
    'Draw No Bet': 'both',
    'First Goal Scorer': 'both',
    'Free Kicks': 'both',
    'Goal Kicks': 'both',
    'Half Time Full Time': 'both',
    'Half Time Result': 'both',
    'Match Corners': 'both',
    'Match Offsides': 'both',
    'Match Result': 'both',
    'Match Shots': 'both',
    'Match Shots On Target': 'both',
    'Match Tackles': 'both',
    'Number of Cards In Match': 'both',
    'Team To Get Most Corners': 'both',
    'Team Goals': 'both',
    'Throw-ins': 'both',
    'Total Shots on Target Home': 'both'
};
