#!/usr/bin/env python3
"""Regenerate src/lib/bookmakers.ts from the Top100 complete bookmaker list.

Scrapes https://www.top100bookmakers.com/completelist.php, pairing each table
row's `data-name` with its `/buttons/<slug>-button.png` image, then writes the
full Record<string, BookmakerMeta> map plus the type-ahead suggestion list and
helper functions used across the Track UI (new-bet combobox, bets table, etc.).

Usage:
    python3 scripts/gen_bookmakers.py

Re-run whenever Top100 adds new bookmakers. Only stdlib is required.
"""

import json
import re
import sys
import urllib.request
from pathlib import Path

SOURCE_URL = "https://www.top100bookmakers.com/completelist.php"
OUT_PATH = Path(__file__).resolve().parent.parent / "src" / "lib" / "bookmakers.ts"

# Hand-curated typed-shorthand aliases that are not present as data-name rows but
# are useful when a user types a variant. These are merged on top of the scrape.
ALIASES = {
    "bet 365": ("Bet365", "bet365"),
    "betfair exchange": ("Betfair Exchange", "betfair"),
    "grosvenor": ("Grosvenor Casinos", "grosvenor-casinos"),
    "grosvenor casinos": ("Grosvenor Casinos", "grosvenor-casinos"),
    "paddy": ("Paddy Power", "paddy-power"),
    "sky bet": ("Sky Bet", "skybet"),
    "willhill": ("William Hill", "william-hill"),
    "william hill": ("William Hill", "william-hill"),
}

BUTTON_RE = re.compile(r"/buttons/([a-z0-9-]+)-button\.(?:png|jpe?g|gif|webp)", re.I)
DATA_NAME_RE = re.compile(r'data-name="([^"]+)"')


def fetch_html(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8", errors="ignore")


def parse_pairs(html: str) -> dict[str, tuple[str, str]]:
    """Map lowercased name -> (display name, button slug). First occurrence wins."""
    pairs: dict[str, tuple[str, str]] = {}
    for row in re.split(r"(?=<tr\b)", html):
        name_m = DATA_NAME_RE.search(row)
        if not name_m:
            continue
        slug_m = BUTTON_RE.search(row)
        if not slug_m:
            continue
        name = name_m.group(1).strip()
        key = name.lower()
        if key not in pairs:
            pairs[key] = (name, slug_m.group(1).lower())
    return pairs


def build_ts(merged: dict[str, tuple[str, str]]) -> str:
    entries = []
    for key in sorted(merged):
        name, slug = merged[key]
        entries.append(
            f"    {json.dumps(key, ensure_ascii=False)}: "
            f"{{ name: {json.dumps(name, ensure_ascii=False)}, "
            f"slug: {json.dumps(slug, ensure_ascii=False)} }},"
        )
    body = "\n".join(entries)
    return (
        "export type BookmakerMeta = {\n"
        "    name: string;\n"
        "    slug: string;\n"
        "};\n\n"
        "// AUTO-GENERATED by scripts/gen_bookmakers.py from\n"
        f"// {SOURCE_URL} (data-name + /buttons/<slug>-button.png),\n"
        "// merged with hand-curated typed-shorthand aliases. Do not edit by hand -\n"
        "// re-run `python3 scripts/gen_bookmakers.py` to refresh.\n"
        "const BOOKMAKER_META: Record<string, BookmakerMeta> = {\n"
        f"{body}\n"
        "};\n\n"
        "/** Sorted, de-duplicated list of known bookmaker display names for type-ahead suggestions. */\n"
        "export const BOOKMAKER_SUGGESTIONS: string[] = Array.from(\n"
        "    new Set(Object.values(BOOKMAKER_META).map((meta) => meta.name))\n"
        ").sort((a, b) => a.localeCompare(b));\n\n"
        "export function normalizeBookmakerKey(value: unknown) {\n"
        "    return String(value || '').trim().toLowerCase().replace(/\\s+/g, ' ');\n"
        "}\n\n"
        "export function titleCaseBookmaker(value: unknown) {\n"
        "    const bookmaker = String(value || '').trim();\n"
        "    if (!bookmaker) return '-';\n"
        "    return bookmaker\n"
        "        .split(' ')\n"
        "        .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())\n"
        "        .join(' ');\n"
        "}\n\n"
        "export function getBookmakerMeta(value: unknown) {\n"
        "    const key = normalizeBookmakerKey(value);\n"
        "    return BOOKMAKER_META[key] || { name: titleCaseBookmaker(value), slug: key.replace(/[^a-z0-9]+/g, '-') };\n"
        "}\n\n"
        "export function getBookmakerButtonUrl(value: unknown) {\n"
        "    const meta = getBookmakerMeta(value);\n"
        "    if (!meta.slug) return '';\n"
        "    return `https://www.top100bookmakers.com/buttons/${meta.slug}-button.png`;\n"
        "}\n"
    )


def main() -> int:
    print(f"Fetching {SOURCE_URL} ...")
    html = fetch_html(SOURCE_URL)
    pairs = parse_pairs(html)
    if len(pairs) < 100:
        print(f"ERROR: only parsed {len(pairs)} bookmakers - page layout may have changed.", file=sys.stderr)
        return 1

    merged: dict[str, tuple[str, str]] = dict(pairs)
    merged.update(ALIASES)

    OUT_PATH.write_text(build_ts(merged), encoding="utf-8")
    unique_names = len({name for name, _ in merged.values()})
    print(f"Wrote {OUT_PATH.relative_to(OUT_PATH.parents[2])} "
          f"({len(merged)} keys, {unique_names} unique bookmakers).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
